Change the default --platforms to host, and restrict the allowed --platforms values.
The current set of allowed --platforms are:

- //build/bazel/platforms:linux_x86_64 (default)
- //build/bazel/platforms:android_target (infers from product config - variables, i.e. lunch)

This list is enforced by the startup --invocation_policy flag. An
invalid --platforms value results in:

    ERROR: Flag value '[//build/bazel/platforms:android_arm64]' for option
    '--platforms' is not allowed by invocation policy and the policy does
    not specify a new value. Allowed values are:
    [//build/bazel/platforms:android_target, //build/bazel/platforms:linux_x86_64]

This will prevent undefined behavior, such as `lunch aosp_arm && b build --config=android_x86_64`.

Given that the host platform is now default, all android cross
compilation commands need to pass --config=android to succeed.

The other platform definitions aren't deleted yet because they're needed
for split transition configuration (e.g. see apex_aab).

Bug: 244766775
Test: presubmits
Change-Id: Ifc0ade319543f2c2c5e8581e8282ffd86aac67d0