Fix running the b command with --
Since the addition of --profile, b has failed to work when using a
"--" argument to indicate the end of arguments, because --profile would
come after the "--".

The error message is:
ERROR: Skipping '-profile=/ssd/aosp-master/out/bazel_metrics-profile': no such target '//:build/bazel/-profile=/ssd/aosp-master/out/bazel_metrics-profile': target 'build/bazel/-profile=/ssd/aosp-master/out/bazel_metrics-profile' not declared in package '' defined by /ssd/aosp-master/out/soong/workspace/BUILD (Tip: use `query "//:*"` to see all the targets in that package)

Test: b build --config=android -- `bmod adbd`
Change-Id: Iac0fd66b2340ce4fac555619f169eb40d873575b